/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProVerificationRouteImport } from './routes/pro-verification'
import { Route as ProLoginSignupRouteImport } from './routes/pro-login-signup'
import { Route as ProDashboardRouteImport } from './routes/pro-dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ClientLoginSignupRouteImport } from './routes/client-login-signup'
import { Route as ClientDashboardRouteImport } from './routes/client-dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientDashboardIndexRouteImport } from './routes/client-dashboard.index'
import { Route as ClientDashboardTransactionsRouteImport } from './routes/client-dashboard.transactions'
import { Route as ClientDashboardTestimonialsRouteImport } from './routes/client-dashboard.testimonials'
import { Route as ClientDashboardSettingsRouteImport } from './routes/client-dashboard.settings'
import { Route as ClientDashboardProfileRouteImport } from './routes/client-dashboard.profile'
import { Route as ClientDashboardMessagesRouteImport } from './routes/client-dashboard.messages'
import { Route as ClientDashboardCheckoutRouteImport } from './routes/client-dashboard.checkout'
import { Route as ClientDashboardBookingsRouteImport } from './routes/client-dashboard.bookings'
import { Route as ClientDashboardTraderUsernameRouteImport } from './routes/client-dashboard.trader.$username'
import { Route as ClientDashboardCategorySlugRouteImport } from './routes/client-dashboard.category.$slug'
import { Route as ClientDashboardBookingCheckoutIdRouteImport } from './routes/client-dashboard.booking-checkout.$id'
import { Route as ClientDashboardBookIdRouteImport } from './routes/client-dashboard.book.$id'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProVerificationRoute = ProVerificationRouteImport.update({
  id: '/pro-verification',
  path: '/pro-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ProLoginSignupRoute = ProLoginSignupRouteImport.update({
  id: '/pro-login-signup',
  path: '/pro-login-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProDashboardRoute = ProDashboardRouteImport.update({
  id: '/pro-dashboard',
  path: '/pro-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginSignupRoute = ClientLoginSignupRouteImport.update({
  id: '/client-login-signup',
  path: '/client-login-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client-dashboard',
  path: '/client-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardIndexRoute = ClientDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardTransactionsRoute =
  ClientDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => ClientDashboardRoute,
  } as any)
const ClientDashboardTestimonialsRoute =
  ClientDashboardTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => ClientDashboardRoute,
  } as any)
const ClientDashboardSettingsRoute = ClientDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardProfileRoute = ClientDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardMessagesRoute = ClientDashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardCheckoutRoute = ClientDashboardCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardBookingsRoute = ClientDashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ClientDashboardRoute,
} as any)
const ClientDashboardTraderUsernameRoute =
  ClientDashboardTraderUsernameRouteImport.update({
    id: '/trader/$username',
    path: '/trader/$username',
    getParentRoute: () => ClientDashboardRoute,
  } as any)
const ClientDashboardCategorySlugRoute =
  ClientDashboardCategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => ClientDashboardRoute,
  } as any)
const ClientDashboardBookingCheckoutIdRoute =
  ClientDashboardBookingCheckoutIdRouteImport.update({
    id: '/booking-checkout/$id',
    path: '/booking-checkout/$id',
    getParentRoute: () => ClientDashboardRoute,
  } as any)
const ClientDashboardBookIdRoute = ClientDashboardBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => ClientDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/client-dashboard': typeof ClientDashboardRouteWithChildren
  '/client-login-signup': typeof ClientLoginSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pro-dashboard': typeof ProDashboardRoute
  '/pro-login-signup': typeof ProLoginSignupRoute
  '/pro-verification': typeof ProVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/client-dashboard/bookings': typeof ClientDashboardBookingsRoute
  '/client-dashboard/checkout': typeof ClientDashboardCheckoutRoute
  '/client-dashboard/messages': typeof ClientDashboardMessagesRoute
  '/client-dashboard/profile': typeof ClientDashboardProfileRoute
  '/client-dashboard/settings': typeof ClientDashboardSettingsRoute
  '/client-dashboard/testimonials': typeof ClientDashboardTestimonialsRoute
  '/client-dashboard/transactions': typeof ClientDashboardTransactionsRoute
  '/client-dashboard/': typeof ClientDashboardIndexRoute
  '/client-dashboard/book/$id': typeof ClientDashboardBookIdRoute
  '/client-dashboard/booking-checkout/$id': typeof ClientDashboardBookingCheckoutIdRoute
  '/client-dashboard/category/$slug': typeof ClientDashboardCategorySlugRoute
  '/client-dashboard/trader/$username': typeof ClientDashboardTraderUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/client-login-signup': typeof ClientLoginSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pro-dashboard': typeof ProDashboardRoute
  '/pro-login-signup': typeof ProLoginSignupRoute
  '/pro-verification': typeof ProVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/client-dashboard/bookings': typeof ClientDashboardBookingsRoute
  '/client-dashboard/checkout': typeof ClientDashboardCheckoutRoute
  '/client-dashboard/messages': typeof ClientDashboardMessagesRoute
  '/client-dashboard/profile': typeof ClientDashboardProfileRoute
  '/client-dashboard/settings': typeof ClientDashboardSettingsRoute
  '/client-dashboard/testimonials': typeof ClientDashboardTestimonialsRoute
  '/client-dashboard/transactions': typeof ClientDashboardTransactionsRoute
  '/client-dashboard': typeof ClientDashboardIndexRoute
  '/client-dashboard/book/$id': typeof ClientDashboardBookIdRoute
  '/client-dashboard/booking-checkout/$id': typeof ClientDashboardBookingCheckoutIdRoute
  '/client-dashboard/category/$slug': typeof ClientDashboardCategorySlugRoute
  '/client-dashboard/trader/$username': typeof ClientDashboardTraderUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-login': typeof AdminLoginRoute
  '/client-dashboard': typeof ClientDashboardRouteWithChildren
  '/client-login-signup': typeof ClientLoginSignupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pro-dashboard': typeof ProDashboardRoute
  '/pro-login-signup': typeof ProLoginSignupRoute
  '/pro-verification': typeof ProVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/client-dashboard/bookings': typeof ClientDashboardBookingsRoute
  '/client-dashboard/checkout': typeof ClientDashboardCheckoutRoute
  '/client-dashboard/messages': typeof ClientDashboardMessagesRoute
  '/client-dashboard/profile': typeof ClientDashboardProfileRoute
  '/client-dashboard/settings': typeof ClientDashboardSettingsRoute
  '/client-dashboard/testimonials': typeof ClientDashboardTestimonialsRoute
  '/client-dashboard/transactions': typeof ClientDashboardTransactionsRoute
  '/client-dashboard/': typeof ClientDashboardIndexRoute
  '/client-dashboard/book/$id': typeof ClientDashboardBookIdRoute
  '/client-dashboard/booking-checkout/$id': typeof ClientDashboardBookingCheckoutIdRoute
  '/client-dashboard/category/$slug': typeof ClientDashboardCategorySlugRoute
  '/client-dashboard/trader/$username': typeof ClientDashboardTraderUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/admin-login'
    | '/client-dashboard'
    | '/client-login-signup'
    | '/forgot-password'
    | '/pro-dashboard'
    | '/pro-login-signup'
    | '/pro-verification'
    | '/reset-password'
    | '/reviews'
    | '/client-dashboard/bookings'
    | '/client-dashboard/checkout'
    | '/client-dashboard/messages'
    | '/client-dashboard/profile'
    | '/client-dashboard/settings'
    | '/client-dashboard/testimonials'
    | '/client-dashboard/transactions'
    | '/client-dashboard/'
    | '/client-dashboard/book/$id'
    | '/client-dashboard/booking-checkout/$id'
    | '/client-dashboard/category/$slug'
    | '/client-dashboard/trader/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/admin-login'
    | '/client-login-signup'
    | '/forgot-password'
    | '/pro-dashboard'
    | '/pro-login-signup'
    | '/pro-verification'
    | '/reset-password'
    | '/reviews'
    | '/client-dashboard/bookings'
    | '/client-dashboard/checkout'
    | '/client-dashboard/messages'
    | '/client-dashboard/profile'
    | '/client-dashboard/settings'
    | '/client-dashboard/testimonials'
    | '/client-dashboard/transactions'
    | '/client-dashboard'
    | '/client-dashboard/book/$id'
    | '/client-dashboard/booking-checkout/$id'
    | '/client-dashboard/category/$slug'
    | '/client-dashboard/trader/$username'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/admin-login'
    | '/client-dashboard'
    | '/client-login-signup'
    | '/forgot-password'
    | '/pro-dashboard'
    | '/pro-login-signup'
    | '/pro-verification'
    | '/reset-password'
    | '/reviews'
    | '/client-dashboard/bookings'
    | '/client-dashboard/checkout'
    | '/client-dashboard/messages'
    | '/client-dashboard/profile'
    | '/client-dashboard/settings'
    | '/client-dashboard/testimonials'
    | '/client-dashboard/transactions'
    | '/client-dashboard/'
    | '/client-dashboard/book/$id'
    | '/client-dashboard/booking-checkout/$id'
    | '/client-dashboard/category/$slug'
    | '/client-dashboard/trader/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ClientDashboardRoute: typeof ClientDashboardRouteWithChildren
  ClientLoginSignupRoute: typeof ClientLoginSignupRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProDashboardRoute: typeof ProDashboardRoute
  ProLoginSignupRoute: typeof ProLoginSignupRoute
  ProVerificationRoute: typeof ProVerificationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-verification': {
      id: '/pro-verification'
      path: '/pro-verification'
      fullPath: '/pro-verification'
      preLoaderRoute: typeof ProVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-login-signup': {
      id: '/pro-login-signup'
      path: '/pro-login-signup'
      fullPath: '/pro-login-signup'
      preLoaderRoute: typeof ProLoginSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-dashboard': {
      id: '/pro-dashboard'
      path: '/pro-dashboard'
      fullPath: '/pro-dashboard'
      preLoaderRoute: typeof ProDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-login-signup': {
      id: '/client-login-signup'
      path: '/client-login-signup'
      fullPath: '/client-login-signup'
      preLoaderRoute: typeof ClientLoginSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-dashboard': {
      id: '/client-dashboard'
      path: '/client-dashboard'
      fullPath: '/client-dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-dashboard/': {
      id: '/client-dashboard/'
      path: '/'
      fullPath: '/client-dashboard/'
      preLoaderRoute: typeof ClientDashboardIndexRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client-dashboard/transactions': {
      id: '/client-dashboard/transactions'
      path: '/transactions'
      fullPath: '/client-dashboard/transactions'
      preLoaderRoute: typeof ClientDashboardTransactionsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client-dashboard/testimonials': {
      id: '/client-dashboard/testimonials'
      path: '/testimonials'
      fullPath: '/client-dashboard/testimonials'
      preLoaderRoute: typeof ClientDashboardTestimonialsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client-dashboard/settings': {
      id: '/client-dashboard/settings'
      path: '/settings'
      fullPath: '/client-dashboard/settings'
      preLoaderRoute: typeof ClientDashboardSettingsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client-dashboard/profile': {
      id: '/client-dashboard/profile'
      path: '/profile'
      fullPath: '/client-dashboard/profile'
      preLoaderRoute: typeof ClientDashboardProfileRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client-dashboard/messages': {
      id: '/client-dashboard/messages'
      path: '/messages'
      fullPath: '/client-dashboard/messages'
      preLoaderRoute: typeof ClientDashboardMessagesRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client-dashboard/checkout': {
      id: '/client-dashboard/checkout'
      path: '/checkout'
      fullPath: '/client-dashboard/checkout'
      preLoaderRoute: typeof ClientDashboardCheckoutRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client-dashboard/bookings': {
      id: '/client-dashboard/bookings'
      path: '/bookings'
      fullPath: '/client-dashboard/bookings'
      preLoaderRoute: typeof ClientDashboardBookingsRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client-dashboard/trader/$username': {
      id: '/client-dashboard/trader/$username'
      path: '/trader/$username'
      fullPath: '/client-dashboard/trader/$username'
      preLoaderRoute: typeof ClientDashboardTraderUsernameRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client-dashboard/category/$slug': {
      id: '/client-dashboard/category/$slug'
      path: '/category/$slug'
      fullPath: '/client-dashboard/category/$slug'
      preLoaderRoute: typeof ClientDashboardCategorySlugRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client-dashboard/booking-checkout/$id': {
      id: '/client-dashboard/booking-checkout/$id'
      path: '/booking-checkout/$id'
      fullPath: '/client-dashboard/booking-checkout/$id'
      preLoaderRoute: typeof ClientDashboardBookingCheckoutIdRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
    '/client-dashboard/book/$id': {
      id: '/client-dashboard/book/$id'
      path: '/book/$id'
      fullPath: '/client-dashboard/book/$id'
      preLoaderRoute: typeof ClientDashboardBookIdRouteImport
      parentRoute: typeof ClientDashboardRoute
    }
  }
}

interface ClientDashboardRouteChildren {
  ClientDashboardBookingsRoute: typeof ClientDashboardBookingsRoute
  ClientDashboardCheckoutRoute: typeof ClientDashboardCheckoutRoute
  ClientDashboardMessagesRoute: typeof ClientDashboardMessagesRoute
  ClientDashboardProfileRoute: typeof ClientDashboardProfileRoute
  ClientDashboardSettingsRoute: typeof ClientDashboardSettingsRoute
  ClientDashboardTestimonialsRoute: typeof ClientDashboardTestimonialsRoute
  ClientDashboardTransactionsRoute: typeof ClientDashboardTransactionsRoute
  ClientDashboardIndexRoute: typeof ClientDashboardIndexRoute
  ClientDashboardBookIdRoute: typeof ClientDashboardBookIdRoute
  ClientDashboardBookingCheckoutIdRoute: typeof ClientDashboardBookingCheckoutIdRoute
  ClientDashboardCategorySlugRoute: typeof ClientDashboardCategorySlugRoute
  ClientDashboardTraderUsernameRoute: typeof ClientDashboardTraderUsernameRoute
}

const ClientDashboardRouteChildren: ClientDashboardRouteChildren = {
  ClientDashboardBookingsRoute: ClientDashboardBookingsRoute,
  ClientDashboardCheckoutRoute: ClientDashboardCheckoutRoute,
  ClientDashboardMessagesRoute: ClientDashboardMessagesRoute,
  ClientDashboardProfileRoute: ClientDashboardProfileRoute,
  ClientDashboardSettingsRoute: ClientDashboardSettingsRoute,
  ClientDashboardTestimonialsRoute: ClientDashboardTestimonialsRoute,
  ClientDashboardTransactionsRoute: ClientDashboardTransactionsRoute,
  ClientDashboardIndexRoute: ClientDashboardIndexRoute,
  ClientDashboardBookIdRoute: ClientDashboardBookIdRoute,
  ClientDashboardBookingCheckoutIdRoute: ClientDashboardBookingCheckoutIdRoute,
  ClientDashboardCategorySlugRoute: ClientDashboardCategorySlugRoute,
  ClientDashboardTraderUsernameRoute: ClientDashboardTraderUsernameRoute,
}

const ClientDashboardRouteWithChildren = ClientDashboardRoute._addFileChildren(
  ClientDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  ClientDashboardRoute: ClientDashboardRouteWithChildren,
  ClientLoginSignupRoute: ClientLoginSignupRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProDashboardRoute: ProDashboardRoute,
  ProLoginSignupRoute: ProLoginSignupRoute,
  ProVerificationRoute: ProVerificationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
